window.onload = function () {
    var who = window.location.href.split('?')[1];
    var id = who.split('=')[1];
    if (id === '1') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/du-lich-bangkok-1-1024x683.webp"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Kinh nghiệm du lịch Bangkok tự túc: ăn - chơi - ở từ A đến Z<h1>';
        document.getElementById('content-1').innerHTML = '<a >Bangkok được biết đến là thiên đường du lịch của Thái Lan. Nơi đây hội tụ tất cả những gì mà một khách du lịch “chân chính” mong muốn như: những trung tâm thương mại sầm uất; những dịch vụ du lịch chất lượng; những loại hình giải trí độc đáo; nền ẩm thực phong phú…Nhưng muốn có chuyến du lịch Bangkok hoàn hảo, bạn đừng quên tìm hiểu trước những kinh nghiệm du lịch Bangkok tự túc này!<a>';
        document.getElementById('content-2').innerHTML = '<a >Không ít du khách lần đầu du lịch Bangkok choáng ngợp với sự hiện đại và sầm uất nơi đây. Bangkok là thủ đô hoa lệ của xứ chùa Vàng với những tòa cao ốc chọc trời, những điểm tham quan hấp dẫn, những loại hình giải trí độc đáo và cả một thiên đường ẩm thực đang chờ bạn khám phá.<a>';
        document.getElementById('content-3').innerHTML = '<a >Bangkok sở hữu nhiều cái “nhất” như: thành phố lớn nhất Thái Lan; thành phố năng động và hiện đại bậc nhất Thái Lan; thành phố có dân bay Suvarnabhumi – một trong những sân bay lớn nhất và bận rộn nhất Châu Á. Cùng khám phá ngay kinh nghiệm du lịch Bangkok bạn nhé!<a>';
    }
    else if (id === '2') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/summer-194030034004-tong-quan-du-lich-han-quoc.jpg"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Kinh Nghiệm Du Lịch Seoul Tự Túc Mới Nhất 2023<h1>';
        document.getElementById('content-1').innerHTML = '<a >Từ kinh nghiệm du lịch Hàn Quốc của mình, để chuyến đi Seoul được thuận lợi thì bạn cần phải chuẩn bị thật kĩ tất cả những đồ dùng cần thiết, bao gồm cả vé máy bay và phòng khách sạn nữa đấy.<a>';
        document.getElementById('content-2').innerHTML = '<a >Quan trọng nhất khi đi du lịch nước ngoài đó là giấy tờ. Bạn cần phải chuẩn bị đầy đủ giấy tờ để có thể xuất - nhập cảnh Seoul Hàn Quốc một cách suôn sẻ nhất mà không lo lắng bị giữ lại.<a>';
        document.getElementById('content-3').innerHTML = '<a >Hộ chiếu là giấy tờ không thể thiếu khi ra nước ngoài. Hãy để ý hộ chiếu của bạn cần phải có hạn tối thiểu là 6 tháng thì mới có thể du lịch nước ngoài được nhé. Đối với trẻ em dưới 2 tuổi phải có cha mẹ đi cùng và phải cung cấp giấy khai sinh để xác minh mối quan hệ của trẻ với cơ quan quản lý khi xuất nhập cảnh.<a>';
    }
    else if (id === '3') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/hoang-thanh-Thang-Long-7703-1652253984.jpg"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Cẩm nang Du lịch HÀ NỘI 2023 từ A-Z: top 15 trải nghiệm phải thử mới nhất<h1>';
        document.getElementById('content-1').innerHTML = '<a >Những công trình từ thời Pháp thuộc, hàng quán vỉa hè bày bán đặc sản địa phương, xe máy luồn lách trên đường đông đúc... là những ấn tượng đầu tiên của du khách về Hà Nội. Với nhiều người, Hà Nội có tất cả những thứ thú vị để khám phá nơi đây theo cách riêng của mình.<a>';
        document.getElementById('content-2').innerHTML = '<a >Thời gian lý tưởng nhất để du lịch Hà Nội là vào mùa thu từ tháng 8 đến tháng 11 và mùa xuân từ tháng 3 đến tháng 4. Không ít người cho rằng mùa thu là lúc tiết trời đẹp nhất trong năm ở Hà Nội, với bầu trời xanh trong, gió heo may se se lạnh, lá vàng rơi, mùi hoa sữa thoảng... Mùa xuân về tiết trời ấm áp, đường phố như thay áo mới khi cây cối đâm chồi nảy lộc, muôn hoa đua nở...<a>';
        document.getElementById('content-3').innerHTML = '<a >Hà Nội được ví như trái tim của Việt Nam, do đó du khách có thể di chuyển thuận lợi đến thủ đô bằng máy bay, tàu hỏa, xe khách, ôtô riêng hay xe máy từ các tỉnh thành khác.<a>';
    }
    else if (id === '4') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/du_lich_hongkong-6.jpg"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Chính thức nới lỏng một số quy định du lịch Hồng Kông, còn chần chờ gì mà không lên lịch ngay!<h1>';
        document.getElementById('content-1').innerHTML = '<a >Vào ngày 7 tháng 11 vừa rồi, chính phủ Hồng Kông vừa có thông báo về lệnh dỡ bỏ những hạn chế du lịch cho các nhóm du khách quốc tế được áp dụng bắt đầu từ tháng này. Các lệnh dỡ bỏ cụ thể bao gồm cho phép các nhóm du khách quốc tế đến Hồng Kông với lịch trình du lịch đã đăng ký trước từ các đại lý du lịch được cấp phép sẽ được cho phép ra vào các địa điểm chỉ định như công viên giải trí, bảo tàng và đền thờ, cũng như dùng bữa tại các cơ sở phục vụ khi sở hữu Mã Amber của Thẻ vắc xin.<a>';
        document.getElementById('content-2').innerHTML = '<a >Tiến sĩ Pang Yiu-kai, Chủ tịch Hội đồng Tổng cục Du lịch Hồng Kông (HKTB) đã bày tỏ sự vui mừng khi đón nhận thông báo mở cửa mới nhất của Chính phủ. Tiến sĩ Pang cho biết: “Các lệnh mở cửa mới đánh dấu sự trở lại của Hồng Kông và gửi một thông điệp tích cực đến khách du lịch và các đối tác thương mại của chúng tôi trên khắp thế giới. Dự kiến, các lệnh mở cửa cụ thể có thể giúp dần dần thu hút khách du lịch giải trí đến thăm lại Hồng Kông, đặc biệt là người tiêu dùng ở các thị trường lân cận. Phía Tổng cục Du lịch Hồng Kông sẽ tiếp tục làm việc với Chính phủ, ngành du lịch và các ngành liên quan để chứng minh sức hấp dẫn du lịch đa dạng của Hồng Kông nhằm tăng cường sở thích của du khách khi đến thăm thành phố, mục tiêu thúc đẩy sự hồi sinh của du lịch tại địa phương. ”<a>';
        document.getElementById('content-3').innerHTML = '<a >Như vậy là giờ đây các tín đồ xê dịch đã có thể an tâm phần nào khi du lịch đến Hồng Kông, đặc biệt là vào mùa lễ hội. Nếu đã đến xứ Cảng Thơm vào dịp cuối năm thì đừng quên check-in bảo tàng mì ly, thùng gạch khổng lồ cùng loạt địa điểm hot mới khai trương nhé.<a>';
    }
    else if (id === '5') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/6e3b-9722-429a-ac40-bac0704661c4.jpg"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Khám Phá Las Vegas - 10 Điểm Check-in Không Thể Bỏ Lỡ!<h1>';
        document.getElementById('content-1').innerHTML = '<a >Khám phá Las Vegas – Las Vegas được ví giống như một ốc đảo chứa đầy sự mê hoặc và quyến rũ, ở đây, bạn sẽ được trải nghiệm cuộc sống của một thành phố không ngủ với các hoạt động liên tục không ngừng nghỉ 24/7. Thậm chí bạn có thể dành toàn bộ thời gian của mình đắm chìm trong các khu phức hợp thay vì đi ra đường khi có khá nhiều hoạt động hấp dẫn ở những khách sạn cao cấp chẳng hạn như: nhâm nhi sâm panh tại các quầy bar bên cạnh những hồ bơi xa hoa, thử vận may tại các sòng bạc hoạt động không ngừng nghỉ hay thể hiện mình tại những sàn nhảy sôi động của những quán bar nổi tiếng.<a>';
        document.getElementById('content-2').innerHTML = '<a >Tuy nhiên, cũng có những vị khách thích khám phá sẽ bước ra thế giới bên ngoài để trải nghiệm vẻ đẹp phong cảnh thiên nhiên ngoạn mục xung quanh Las Vegas. Những cảnh thiên nhiên hùng vĩ được bồi đắp bởi những kiến ​​tạo, được tạc bởi gió và được nung bởi mặt trời sa mạc, những hẻm núi và đồng bằng rộng lớn, những ngọn núi cao và những khu rừng núi hoang sơ vẫy gọi v.v sẽ thách thức bạn đánh đổi sự hưởng thụ xa hoa tại phố thị Las Vegas để nhận lấy cái ôm ấm áp của thiên nhiên.<a>';
        document.getElementById('content-3').innerHTML = '<a >Khách du lịch đến Vegas để tận hưởng sự xa hoa sẽ chắc chắn không thể bỏ qua việc check-in tại những khách sạn cao cấp lớn và sang trọng nhất thế giới. Ở Las Vegas, giá phòng khách sạn dao động trong khoảng $300 mỗi đêm cho một phòng tiêu chuẩn cao cấp tại Encore, Cosmopolitan hoặc Delano, cao cấp hơn một chút sẽ có giá $1000 mỗi đêm cho một SkyLoft tại MGM Grand, $3500 cho một Sky Villa tại Aria và cao cấp nhất có lẽ là khu biệt thự nghỉ dưỡng Nobu với giá $35.000 cho một đêm. Hơn 150.000 phòng khách sạn ở Vegas có đủ hạng phòng mang đến nhiều sự lựa chọn cho du khách với chất lượng trải rộng từ bình dân tới sang chảnh.<a>';
    }
    else if (id === '6') {
        document.getElementById('img').innerHTML = '<img style="display:block;width: 50%;margin: 0 auto;padding: 30px 0;" src=\"img/25729080-20181119104558-hinh-tong-hop-hinh-anh-tong-hop-2.jpg"\ />';
        document.getElementById('title').innerHTML = '<h1 style="text-align:center">Du lịch London, Vương Quốc Anh 2023: kinh nghiệm, cẩm nang, blog, review mới nhất<h1>';
        document.getElementById('content-1').innerHTML = '<a >Luân Đôn là thủ đô của Anh và Vương quốc Liên hiệp Anh và Bắc Ireland, đồng thời là thành phố lớn nhất Vương quốc Liên hiệp Anh và cũng là khu vực đô thị rộng thứ hai về diện tích trong Liên minh châu Âu (EU). Luân Đôn được người La Mã lập ra 2000 năm trước đây với tên gọi đầu tiên là Londinium (Luân Đôn thuộc La Mã). Trung tâm chính từ xa xưa của Luân Đôn là Thành phố Luân Đôn, hiện vẫn giữ được ranh giới rộng hàng dặm vuông từ thời Trung Cổ trên quy mô lớn. Sớm nhất cũng từ thế kỷ 19, tên gọi "Luân Đôn" mới được biết đến như một đô thị lớn phát triển quanh trung tâm chính. Sự sáp nhập của những vùng đô thị liên hoàn tạo thành vùng Luân Đôn và vùng hành chính Đại Luân Đôn do thị trưởng Luân Đôn và Hội đồng Luân Đôn điều hành thông qua đắc cử.<a>';
        document.getElementById('content-2').innerHTML = '<a >Luân Đôn có thành phần dân tộc, văn hóa, tôn giáo đa dạng, có hơn 300 ngôn ngữ được sử dụng. Tại thời điểm tháng 7 năm 2016, thành phố có dân số chính thức là 8,787,892 người trong Đại Luân Đôn, khiến nó là đô thị đông dân nhất Liên minh châu Âu. Vùng đô thị Đại Luân Đôn (Greater London Urban Area) (vùng đô thị lớn thứ hai ở châu Âu) có dân số 9,787,426. Còn vùng đô thị Luân Đôn lớn nhất châu Âu với dân số 14,040,163 người vào năm 2016. Thống kê cho thấy chưa đến 70% dân số Luân Đôn là người da trắng, điều này cho thấy Luân Đôn có tính quốc tế cao. Hệ thống tàu điện ngầm Luân Đôn do Cục vân tải Luân Đôn (Transport for London) quản lý, là hệ thống tàu điện ngầm cổ nhất thế giới. Sân bay Heathrow London là sân bay bận rộn nhất thế giới theo lượt khách quốc tế với không gian hàng không tấp nập hơn bất cứ trung tâm đô thị nào trên thế giới.<a>';
        document.getElementById('content-3').innerHTML = '<a >Giải trí là một phần chính của nền kinh tế Luân Đôn, với một báo cáo năm 2003 ghi nhận một phần tư toàn bộ nền kinh tế giải trí của Anh cho Luân Đôn với 25,6 sự kiện trên 1000 người. Trên toàn cầu, thành phố này là một trong bốn kinh đô thời trang lớn của thế giới, và theo thống kê chính thức, Luân Đôn là trung tâm sản xuất phim bận rộn thứ ba trên thế giới, giới thiệu nhiều phim hài trực tiếp hơn bất kỳ thành phố nào khác, và có lượng khán giả nhà hát lớn nhất bất kỳ thành phố nào trên thế giới<a>';
    }
}